version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - crewai
      - redis     
    restart: unless-stopped

  crewai:
    build:
      context: ./crewai
      dockerfile: Dockerfile
    
    ports:
      - "8004:8004"
    env_file:
      - ./crewai/.env
    volumes:
      - ./crewai:/app
    # command: tail -f /dev/null
    # restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  redis_data: